name = "xugou-backend"
main = "src/index.ts"
compatibility_date = "2025-03-10"
compatibility_flags = ["nodejs_compat"]

# 添加定时触发器，每分钟执行一次监控检查
[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "xugou_db"
database_id = "80b8bb7f-2ca0-4de1-93d6-61bd2b8e11fc"

[version_metadata]
binding = "CF_VERSION_METADATA"
